name:                simple-storage
version:             0.1.0.0
# github:              "f-o-a-m/kepler/hs-abci-docs/simple-storage"
license:             Apache
author:              Martin Allen
maintainer:          "martin@foam.space"
copyright:           "2020 Martin Allen"

extra-source-files:
- protos/**/*.proto

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/kepler/blob/master/hs-abci-docs/simple-storage/README.md>

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

library:
  source-dirs:
  - src
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  dependencies:
    - aeson
    - base >= 4.7 && < 5
    - bytestring
    - cereal
    - cereal-text
    - cryptonite
    - hs-abci-extra
    - hs-abci-server
    - hs-abci-types
    - hs-abci-extra
    - hs-abci-sdk
    - katip
    - lens
    - memory
    - polysemy
    - polysemy-plugin
    - proto-lens
    - proto-lens-runtime
    - servant
    - string-conversions
    - text
    - validation
  exposed-modules:
  - SimpleStorage.Server
  - SimpleStorage.Application
  - SimpleStorage.Config
  - SimpleStorage.Modules.SimpleStorage
  - SimpleStorage.Modules.SimpleStorage.Types
  - SimpleStorage.Modules.SimpleStorage.Keys
  - SimpleStorage.Modules.SimpleStorage.Message
  - SimpleStorage.Modules.SimpleStorage.Keeper
  - SimpleStorage.Modules.SimpleStorage.Router
  - SimpleStorage.Modules.SimpleStorage.Query

  generated-exposed-modules:
  - Proto.SimpleStorage.Messages
  - Proto.SimpleStorage.Messages_Fields

executables:
  simple-storage:
    source-dirs:
    - app
    main: Main.hs
    ghc-options:
    - -Werror
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - base >= 4.7 && < 5
    - katip
    - hs-abci-sdk
    - lens
    - simple-storage

tests:
  simple-storage-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - SimpleStorage.Test.E2ESpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - data-default-class
      - hs-abci-sdk
      - simple-storage
      - hs-abci-test-utils
      - hs-tendermint-client
      - hspec
      - mtl
      - servant
      - random
